### ISSUE TITLE
Error trying to kill Calibre on osx

### ISSUE THREAD

**Issue by paour** [eli-schwartz/calibre-installer#1]
```
$ calibre-upgrade.sh
Calibre is out-of-date. Upgrading...


killall: unknown signal q; valid signals:
HUP INT QUIT ILL TRAP ABRT EMT FPE KILL BUS SEGV SYS PIPE ALRM TERM URG STOP
TSTP CONT CHLD TTIN TTOU IO XCPU XFSZ VTALRM PROF WINCH INFO USR1 USR2
No running calibre servers.
```

**Comment by eli-schwartz** [comment]
I've never tested my (tentative) rewrite for OSX, since I do not own a Mac. I _tried_ to avoid false assumptions, but clearly I missed one. :grinning: 

So apparently it slipped by me that `killall` does not have the same options (`-q -v`) as it does on linux.

I don't suppose you know of any other way to kill a process without reporting ugly "no process found" errors? I only ever added those switches in order to make the output look a little prettier.

...

Nah, probably not worth the bother.

**Comment by eli-schwartz** [comment]
Thanks for being the first one to test this (that I know of)! :smile: 

If you see any other problems, feel free to point them out -- I've never had a chance to see if it works -- I only know the linux script it is based on works quite well, but obviously, that doesn't necessarily mean anything. :smirk:

**Comment by paour** [comment]
Fix verified.

Thank you very much for taking the pain out of keeping Calibre up to date… and for daring to support a platform you're not running.
